--
-- Incremental dump: product deals, escrow payment purpose and deal statuses
--

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'PaymentPurpose') THEN
        CREATE TYPE "PaymentPurpose" AS ENUM ('TOP_UP', 'DEAL_ESCROW');
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'DealStatus') THEN
        CREATE TYPE "DealStatus" AS ENUM (
            'CREATED',
            'PAID',
            'SHIPPED',
            'DELIVERED',
            'DISPUTE',
            'COMPLETED',
            'CANCELLED',
            'REFUNDED'
        );
    END IF;
END $$;

ALTER TABLE public."Payment"
    ADD COLUMN IF NOT EXISTS purpose "PaymentPurpose" NOT NULL DEFAULT 'TOP_UP',
    ADD COLUMN IF NOT EXISTS "dealId" integer;

CREATE TABLE IF NOT EXISTS public."ProductDeal" (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "productId" integer NOT NULL,
    "buyerId" integer NOT NULL,
    "sellerId" integer NOT NULL,
    status "DealStatus" NOT NULL DEFAULT 'CREATED',
    "productAmount" integer NOT NULL,
    "deliveryCost" integer NOT NULL DEFAULT 0,
    "platformFee" integer NOT NULL,
    "sellerAmount" integer NOT NULL,
    "totalAmount" integer NOT NULL,
    "paymentId" text,
    "orderId" text,
    "paymentUrl" text,
    "cdekTariffCode" integer,
    "cdekTariffName" text,
    "cdekFromCityCode" integer,
    "cdekToCityCode" integer,
    "cdekFromPvzCode" text,
    "cdekToPvzCode" text,
    "cdekOrderUuid" text,
    "cdekTrackNumber" text,
    "disputeReason" text,
    "paidAt" timestamp(3) without time zone,
    "shippedAt" timestamp(3) without time zone,
    "deliveredAt" timestamp(3) without time zone,
    "payoutAvailableAt" timestamp(3) without time zone,
    "completedAt" timestamp(3) without time zone,
    "cancelledAt" timestamp(3) without time zone,
    "refundedAt" timestamp(3) without time zone,
    "createdAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ProductDeal_pkey') THEN
        ALTER TABLE ONLY public."ProductDeal" ADD CONSTRAINT "ProductDeal_pkey" PRIMARY KEY (id);
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS "ProductDeal_paymentId_key" ON public."ProductDeal"("paymentId");
CREATE UNIQUE INDEX IF NOT EXISTS "ProductDeal_orderId_key" ON public."ProductDeal"("orderId");
CREATE INDEX IF NOT EXISTS "ProductDeal_productId_idx" ON public."ProductDeal"("productId");
CREATE INDEX IF NOT EXISTS "ProductDeal_buyerId_idx" ON public."ProductDeal"("buyerId");
CREATE INDEX IF NOT EXISTS "ProductDeal_sellerId_idx" ON public."ProductDeal"("sellerId");
CREATE INDEX IF NOT EXISTS "ProductDeal_status_idx" ON public."ProductDeal"(status);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ProductDeal_productId_fkey') THEN
        ALTER TABLE public."ProductDeal" ADD CONSTRAINT "ProductDeal_productId_fkey"
            FOREIGN KEY ("productId") REFERENCES public."Product"(id) ON DELETE CASCADE ON UPDATE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ProductDeal_buyerId_fkey') THEN
        ALTER TABLE public."ProductDeal" ADD CONSTRAINT "ProductDeal_buyerId_fkey"
            FOREIGN KEY ("buyerId") REFERENCES public."User"(id) ON DELETE CASCADE ON UPDATE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ProductDeal_sellerId_fkey') THEN
        ALTER TABLE public."ProductDeal" ADD CONSTRAINT "ProductDeal_sellerId_fkey"
            FOREIGN KEY ("sellerId") REFERENCES public."User"(id) ON DELETE CASCADE ON UPDATE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Payment_dealId_fkey') THEN
        ALTER TABLE public."Payment" ADD CONSTRAINT "Payment_dealId_fkey"
            FOREIGN KEY ("dealId") REFERENCES public."ProductDeal"(id) ON DELETE SET NULL ON UPDATE CASCADE;
    END IF;
END $$;

INSERT INTO public._prisma_migrations (
    id,
    checksum,
    finished_at,
    migration_name,
    logs,
    rolled_back_at,
    started_at,
    applied_steps_count
)
SELECT
    'd6df9263-6930-4585-a1c0-634be0db9c9a',
    '9312c1636b97b192b47fe14ef0df7b3d0fb1ae664fac71b5e6895162e1142628',
    CURRENT_TIMESTAMP,
    '20260411000100_add_product_deals_escrow',
    '',
    NULL,
    CURRENT_TIMESTAMP,
    1
WHERE EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = '_prisma_migrations'
)
AND NOT EXISTS (
    SELECT 1
    FROM public._prisma_migrations
    WHERE migration_name = '20260411000100_add_product_deals_escrow'
);
