# .air.toml — hot reload для api-go
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ./cmd/server"
  bin = "./tmp/main.exe"
  full_bin = "./tmp/main.exe"
  include_ext = ["go", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", "docs"]
  delay = 1000

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = false
