// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/address/suggestions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "address"
                ],
                "summary": "Подсказки адреса (DaData)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Строка поиска",
                        "name": "query",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 5,
                        "description": "Лимит",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object"
                            }
                        }
                    }
                }
            }
        },
        "/address/validate": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "address"
                ],
                "summary": "Проверка адреса по первой подсказке DaData",
                "parameters": [
                    {
                        "description": "Адрес",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.swaggerValidateAddress"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/change-password": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Новый пароль после verify-code",
                "parameters": [
                    {
                        "description": "Тело",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.swaggerChangePassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/forgot-password": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Запрос кода сброса на почту",
                "parameters": [
                    {
                        "description": "email",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.swaggerForgotEmail"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/isAdmin": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Проверка роли admin",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Выход",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Текущий пользователь",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/auth/sign-in": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Вход (ставит cookie session_id)",
                "parameters": [
                    {
                        "description": "Логин",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.swaggerSignIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/auth/sign-up": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация — отправка кода (query where=telegram|sms)",
                "parameters": [
                    {
                        "enum": [
                            "telegram",
                            "sms"
                        ],
                        "type": "string",
                        "description": "telegram или sms",
                        "name": "where",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Данные",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.swaggerSignUp"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/verify-code": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Проверка кода сброса",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Код из письма",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        },
        "/auth/verify-mobile-code": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Подтверждение телефона по коду",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Код из SMS/TG",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/banner": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "banner"
                ],
                "summary": "Список одобренных баннеров (query place опционально)",
                "responses": {}
            },
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "banner"
                ],
                "summary": "Создать баннер (multipart: image, name, place, navigateToUrl; сессия)",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/banner/all-banners-to-moderate": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "banner"
                ],
                "summary": "Очередь баннеров на модерацию (admin)",
                "responses": {}
            }
        },
        "/banner/moderate/{id}": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "banner"
                ],
                "summary": "Модерация баннера (admin, query status)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Banner id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "MODERATE|APPROVED|DENIDED",
                        "name": "status",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/banner/random": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "banner"
                ],
                "summary": "Случайные одобренные баннеры",
                "responses": {}
            }
        },
        "/category/create-category": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "category-admin"
                ],
                "summary": "Создать категорию",
                "parameters": [
                    {
                        "description": "Тело",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.swaggerCreateCategory"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/category/delete-category/{id}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "category-admin"
                ],
                "summary": "Удалить категорию",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/category/find-all": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "category"
                ],
                "summary": "Дерево всех категорий",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object"
                            }
                        }
                    }
                }
            }
        },
        "/category/find-by-id/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "category"
                ],
                "summary": "Категория по id (полное дерево)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID категории",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/category/path/{slugPath}": {
            "get": {
                "description": "В Swagger «Try it out» введи сегменты через %2F, например: elektronika%2Ftelefony",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "category"
                ],
                "summary": "Разрешение цепочки slug (категория / подкатегория / тип)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Цепочка (или один сегмент)",
                        "name": "slugPath",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/category/slug/{slug}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "category"
                ],
                "summary": "Категория по slug",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/category/update-category/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "category-admin"
                ],
                "summary": "Обновить категорию",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Тело",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.swaggerUpdateCategory"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/chat": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Список чатов пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object"
                            }
                        }
                    }
                }
            }
        },
        "/chat/start": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Начать чат по товару",
                "parameters": [
                    {
                        "description": "productId",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.swaggerStartChat"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/chat/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Информация о чате",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Chat id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/chat/{id}/messages": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Сообщения чата (пагинация)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Chat id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Страница",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Лимит",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Возвращает status ok",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Проверка живости сервиса",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/log/find-all": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "log"
                ],
                "summary": "Список записей Log",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object"
                            }
                        }
                    }
                }
            }
        },
        "/payment/check-status": {
            "post": {
                "description": "Сессия: cookie session_id. В теле — paymentId из ответа Init или уведомления.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payment"
                ],
                "summary": "Проверка статуса платежа в Т-Банке (GetState)",
                "parameters": [
                    {
                        "description": "paymentId",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.swaggerCheckPayment"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.swaggerPaymentCheckStateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/payment/create": {
            "post": {
                "description": "Init в Т-Банк. Нужны TINKOFF_TERMINAL_KEY и TINKOFF_SECRET_KEY. Авторизация: cookie session_id после POST /auth/sign-in.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payment"
                ],
                "summary": "Создание платежа для пополнения баланса",
                "parameters": [
                    {
                        "description": "Сумма в рублях (мин. 1)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.swaggerCreatePayment"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.swaggerPaymentCreateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/payment/history": {
            "get": {
                "description": "До 50 записей, новые сверху. Сессия: cookie session_id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payment"
                ],
                "summary": "История платежей пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.swaggerPaymentHistoryItem"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/payment/notification": {
            "post": {
                "description": "Без сессии. Подпись Token проверяется по полям тела. Тело — как приходит от банка; пример ниже.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payment"
                ],
                "summary": "Webhook уведомлений Т-Банка о статусе платежа",
                "parameters": [
                    {
                        "description": "Уведомление",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.swaggerTinkoffNotification"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.swaggerPaymentNotifyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/product/all-products": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product"
                ],
                "summary": "Список товаров / поиск (query; optional сессия для избранного)",
                "responses": {}
            }
        },
        "/product/create": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product"
                ],
                "summary": "Создать товар (multipart, до 8 images, сессия)",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/product/moderate-product/{id}": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product-admin"
                ],
                "summary": "Модерация (admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "APPROVED|DENIDED",
                        "name": "status",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Причина при DENIDED",
                        "name": "reason",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/product/product-card/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product"
                ],
                "summary": "Карточка товара",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/product/{id}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product"
                ],
                "summary": "Удалить свой товар",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "patch": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product"
                ],
                "summary": "Обновить товар (multipart)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/promotion/add-promotion": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "promotion"
                ],
                "summary": "Подключить продвижение к товару (сессия)",
                "parameters": [
                    {
                        "description": "Тело",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.swaggerAddPromotion"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/promotion/all-promotions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "promotion"
                ],
                "summary": "Все типы продвижения (тарифы)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object"
                            }
                        }
                    }
                }
            }
        },
        "/review/all-reviews-to-moderate": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "review-admin"
                ],
                "summary": "Очередь отзывов на модерацию (admin)",
                "responses": {}
            }
        },
        "/review/moderate-review/{id}": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "review-admin"
                ],
                "summary": "Модерация отзыва (admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Review id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "APPROVED|DENIDED",
                        "name": "status",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/review/send-review": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "review"
                ],
                "summary": "Оставить отзыв продавцу (сессия)",
                "parameters": [
                    {
                        "description": "Тело",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.swaggerSendReview"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/review/user-reviews/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "review"
                ],
                "summary": "Одобренные отзывы о пользователе",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/statistics/analytic": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statistics"
                ],
                "summary": "Статистика пользователя (просмотры, телефон, избранное)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "day week month quarter half-year year",
                        "name": "period",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Фильтр по категории (через SubCategory)",
                        "name": "categoryId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Подстрока в address (ILIKE)",
                        "name": "region",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Конкретный товар",
                        "name": "productId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/statistics/products-analytic": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statistics"
                ],
                "summary": "Аналитика по каждому товару продавца",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object"
                            }
                        }
                    }
                }
            }
        },
        "/subcategory-type/find-all": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subcategory-type"
                ],
                "summary": "Все типы подкатегорий",
                "responses": {}
            }
        },
        "/subcategory-type/find-by-id/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subcategory-type"
                ],
                "summary": "Тип подкатегории по id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/subcategory/find-all": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subcategory"
                ],
                "summary": "Список подкатегорий",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object"
                            }
                        }
                    }
                }
            }
        },
        "/subcategory/find-by-id/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subcategory"
                ],
                "summary": "Подкатегория по id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/support/stats": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "support"
                ],
                "summary": "Статистика тикетов (только admin)",
                "responses": {}
            }
        },
        "/support/tickets": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "support"
                ],
                "summary": "Создать тикет поддержки",
                "parameters": [
                    {
                        "description": "Тело",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.swaggerCreateSupportTicket"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/support/tickets/all": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "support"
                ],
                "summary": "Все тикеты (модератор/admin)",
                "responses": {}
            }
        },
        "/support/tickets/my": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "support"
                ],
                "summary": "Мои тикеты (пагинация, фильтры query)",
                "responses": {}
            }
        },
        "/support/tickets/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "support"
                ],
                "summary": "Тикет с сообщениями",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ticket id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "support"
                ],
                "summary": "Обновить тикет (модератор/admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ticket id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Поля",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.swaggerUpdateSupportTicket"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/support/tickets/{id}/assign": {
            "put": {
                "tags": [
                    "support"
                ],
                "summary": "Назначить тикет на себя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ticket id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/support/tickets/{id}/messages": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "support"
                ],
                "summary": "Сообщение в тикет",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ticket id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Текст",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.swaggerSupportMessage"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/type-field/find-all": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "type-field"
                ],
                "summary": "Все характеристики (поля типа)",
                "responses": {}
            }
        },
        "/type-field/find-by-id/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "type-field"
                ],
                "summary": "Характеристика по id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/user/find-all": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-admin"
                ],
                "summary": "Список пользователей (админ: cookie session_id + роль admin)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/user/info/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Карточка пользователя (рейтинг, лимит объявлений)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/user/remaining-free-ads": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Остаток бесплатных объявлений (сессия)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/user/set-balance/{userId}": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-admin"
                ],
                "summary": "Установить bonusBalance (админ, сессия)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User id",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Число",
                        "name": "balance",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user/show-number/{userId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Показать номер продавца (сессия)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Продавец",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user/toggle-banned/{id}": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-admin"
                ],
                "summary": "Бан / разбан (админ, сессия)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user/update-settings": {
            "patch": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Обновление настроек (multipart, сессия)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ФИО",
                        "name": "fullName",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Телефон",
                        "name": "phoneNumber",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "true/false",
                        "name": "isAnswersCall",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "INDIVIDUAL|OOO|IP",
                        "name": "profileType",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Аватар",
                        "name": "photo",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/user/verify-code": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Подтвердить почту по коду из письма",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Код",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user/verify-email": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Отправить код подтверждения на почту (сессия)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user/{id}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-admin"
                ],
                "summary": "Удалить пользователя (админ, сессия)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-admin"
                ],
                "summary": "Обновить пользователя (админ, сессия)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Поля",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.swaggerAdminUpdateUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.swaggerAddPromotion": {
            "type": "object",
            "properties": {
                "days": {
                    "type": "integer",
                    "example": 7
                },
                "productId": {
                    "type": "integer",
                    "example": 123
                },
                "promotionId": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "main.swaggerAdminUpdateUser": {
            "type": "object",
            "properties": {
                "bonusBalance": {
                    "type": "number"
                },
                "email": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "profileType": {
                    "type": "string"
                }
            }
        },
        "main.swaggerChangePassword": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "main.swaggerCheckPayment": {
            "type": "object",
            "properties": {
                "paymentId": {
                    "type": "string",
                    "example": "2673412345"
                }
            }
        },
        "main.swaggerCreateCategory": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Автомобили"
                },
                "slug": {
                    "type": "string",
                    "example": "avtomobili"
                }
            }
        },
        "main.swaggerCreatePayment": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 1000
                },
                "description": {
                    "type": "string",
                    "example": "Пополнение баланса"
                }
            }
        },
        "main.swaggerCreateSupportTicket": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "priority": {
                    "type": "string",
                    "example": "MEDIUM"
                },
                "subject": {
                    "type": "string"
                },
                "theme": {
                    "type": "string",
                    "example": "TECHNICAL_ISSUE"
                }
            }
        },
        "main.swaggerForgotEmail": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "main.swaggerPaymentCheckStateResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 1000
                },
                "orderId": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "example": "CONFIRMED"
                }
            }
        },
        "main.swaggerPaymentCreateResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 1000
                },
                "orderId": {
                    "type": "string",
                    "example": "123-1735123456789"
                },
                "paymentId": {
                    "type": "string",
                    "example": "2673412345"
                },
                "paymentUrl": {
                    "type": "string",
                    "example": "https://securepay.tinkoff.ru/..."
                }
            }
        },
        "main.swaggerPaymentHistoryItem": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "orderId": {
                    "type": "string"
                },
                "paymentId": {
                    "type": "string"
                },
                "paymentUrl": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "example": "COMPLETED"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "main.swaggerPaymentNotifyResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Баланс успешно пополнен"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "main.swaggerSendReview": {
            "type": "object",
            "properties": {
                "rating": {
                    "type": "number",
                    "example": 5
                },
                "reviewedUserId": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "main.swaggerSignIn": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "main.swaggerSignUp": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                }
            }
        },
        "main.swaggerStartChat": {
            "type": "object",
            "properties": {
                "productId": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "main.swaggerSupportMessage": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string"
                }
            }
        },
        "main.swaggerTinkoffNotification": {
            "type": "object",
            "properties": {
                "Amount": {
                    "type": "integer",
                    "example": 100000
                },
                "ErrorCode": {
                    "type": "string",
                    "example": "0"
                },
                "OrderId": {
                    "type": "string",
                    "example": "123-1735123456789"
                },
                "Pan": {
                    "type": "string",
                    "example": "430000******0777"
                },
                "PaymentId": {
                    "type": "string",
                    "example": "2673412345"
                },
                "Status": {
                    "type": "string",
                    "example": "CONFIRMED"
                },
                "Success": {
                    "type": "boolean",
                    "example": true
                },
                "TerminalKey": {
                    "type": "string",
                    "example": "1766153689307DEMO"
                },
                "Token": {
                    "type": "string",
                    "example": "подпись_от_банка"
                }
            }
        },
        "main.swaggerUpdateCategory": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Автомобили"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "main.swaggerUpdateSupportTicket": {
            "type": "object",
            "properties": {
                "priority": {
                    "type": "string",
                    "example": "HIGH"
                },
                "status": {
                    "type": "string",
                    "example": "IN_PROGRESS"
                }
            }
        },
        "main.swaggerValidateAddress": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "addressDetails": {}
            }
        }
    },
    "tags": [
        {
            "description": "Socket.IO на ` + "`" + `/socket.io` + "`" + ` (см. блок **Socket.IO** в описании API выше). В Swagger нет Try it out для WS.",
            "name": "websocket"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Med Vito REST API (Go)",
	Description:      "REST API (Go/Fiber). Документация и Try it out: GET /docs/index.html. Для цепочки slug в path используй %2F (например elektronika%2Ftelefony).\n**Socket.IO:** тот же хост и CORS что у REST; путь `/socket.io`; авторизация cookie `session_id`. Неймспейсы `/chat` и `/support`.\nКлиент `socket.io`: надёжнее **v2.x / v3.x**; движок Go (`googollee/go-socket.io` ~v1.7) часто **не коннектится** с **socket.io-client v4** из‑за протокола handshake.\n**/chat** — исходящие: `joinChat` {chatId}, `sendMessage` {chatId, content}, `markAsRead` {chatId}. Входящие: `newMessage`, `messagesRead`, `newChatMessage`.\n**/support** — исходящие: `joinTicket`, `leaveTicket`, `sendSupportMessage` {ticketId, message:{text}}, `supportTyping` {ticketId, isTyping}, `updateTicketStatus` {ticketId, status} (модератор). Входящие: `newSupportMessage`, `moderatorResponse`, `supportUserTyping`, `ticketStatusUpdated`; по неймспейсу `newSupportTicket`; в комнате тикета `ticketAssigned`.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
